### PR TITLE
Fix race condition in a _send_cmd()

### PR DESCRIPTION
**Pull request by PaulAnnekov**
Quick fix for #45 by creating separate socket for each send.

This line should be removed after merge to make build successful: https://github.com/Danielhiversen/PyXiaomiGateway/blob/b7407d22118529d17bbfd99050f755edfc085c74/tests/test_e2e.py#L96

### CODE REVIEW

**Comment by Barrysv** [comment]
@PaulAnnekov - saw the message yesterday 3 times in the logs - Haven't seen it come up again today but in the previous version (<0.11.0) I only got the error messages sporadically.  I have 8 xiaomi switches, 2 motion sensors, 4 temp/humidity sensors, 2 lights, 3 IR remotes working in my network (separate vlan).  Do I need to pull the dev 0.80.0 homeassistant to make use of the updated features in 0.11.0? Cheers

**Comment by PaulAnnekov** [comment]
> Do I need to pull the dev 0.80.0 homeassistant to make use of the updated features in 0.11.0

No.

> saw the message yesterday 3 times in the logs

It's hard to debug this issue w/o your logs.

**Comment by Barrysv** [comment]
2018-10-08 21:01:55 WARNING (MainThread) [homeassistant.bootstrap] Skipping
pip installation of required modules. This may cause issues
2018-10-08 21:01:55 WARNING (MainThread) [homeassistant.components.http]
legacy_api_password support has been enabled. If you don't require it,
remove the 'api_password' from your http config.
2018-10-08 21:02:01 WARNING (MainThread) [homeassistant.loader] You are
using a custom component for sensor.technicolor which has not been tested
by Home Assistant. This component might cause stability problems
, be sure to disable it if you do experience issues with Home Assistant.
2018-10-09 07:20:29 ERROR (Thread-2) [xiaomi_gateway] Cannot connect to
Gateway
2018-10-09 07:20:29 ERROR (Thread-2) [xiaomi_gateway] No data in response
from hub None


Hi Paul, this is a pretty short log - I restarted last night after
reconfiguring iOS notifications.  The technicolor sensor is a custom
component that reads from my technicolor modem.  It has been running well
for the past 2 months.

**Comment by PaulAnnekov** [comment]
@Barrysv add config for additional logs:
```
logger:
  logs:
    xiaomi_gateway: debug
    homeassistant.components.xiaomi_aqara: debug
```

**Comment by Barrysv** [comment]
@PaulAnnekov I've uploaded an extract from the log. It starts getting interesting around 15:41:08 when a motion sensor triggers a few lights and we see the connection error occur. Thanks

[home_asistant_xiaomi_debug_log.txt](https://github.com/Danielhiversen/PyXiaomiGateway/files/2463698/home_asistant_xiaomi_debug_log.txt)

**Comment by PaulAnnekov** [comment]
@Barrysv ok, I see. HA sends 2 requests in parallel, but receives response only for one.
Try to collect these erroneous cases and find a pattern:
- does it happen only when multiple simultaneous requests running or it happens even for single request?
- does it happen only for specific devices, like plug and gateway or for other devices too?

**Comment by Barrysv** [comment]
@PaulAnnekov- so far it certainly seems to be the case that when two simultaneous requests are triggered, sometimes only one acknowledgement comes back from the gateway.  In this new log you see an automation trigger the state of a HA group and again the gateway (internal light) is one of the entities.  I have other scripts that trigger multiple xiaomi switches (both on and off) but haven't yet seen them misbehave in this latest version.  I have tried toggling groups in HA that affect multiple xiaomi switch entities and the internal gateway light but haven't yet seen the error to show on demand. Will keep monitoring
[home_asistant_xiaomi_debug_log_2.txt](https://github.com/Danielhiversen/PyXiaomiGateway/files/2467283/home_asistant_xiaomi_debug_log_2.txt)

**Comment by Barrysv** [comment]
@PaulAnnekov It seems that most of the time the Xiaomi gateway can handle two simultaneous requests - but on occasion only one ack comes back. See filtered log attached
[xiaomi_cmd_summary.txt](https://github.com/Danielhiversen/PyXiaomiGateway/files/2471232/xiaomi_cmd_summary.txt)

**Comment by PaulAnnekov** [comment]
Run:

```
git clone https://github.com/Danielhiversen/PyXiaomiGateway.git
cd PyXiaomiGateway
pip install -e .
```

Download file [test.txt](https://github.com/Danielhiversen/PyXiaomiGateway/files/2476328/test.txt) into `PyXiaomiGateway` folder, rename to `test.py`.  Run:

`python3 test.py 34ce0088c937 158d00010decac [key] on`

It will switch on/off gateway and plug 20 times simultaneously. You can execute it multiple times. Check if errors appear during execution.

**Comment by Barrysv** [comment]
Hi Paul, I just tested it and can run it several times without any errors.  But on occasion I do notice an invalid key error (apologies for the screen shot attached instead of a log file). I ran this test.py in my homeassistant virtual environment so I didn't need to clone the gateway git and home assistant was running in the background also.  I have noticed now in HA 0.80 since there is more frequent polling of the switch power status I have noticed that in the HA logs some switch requests don't get a reply
e8945f5b-f2a8-4716-91e2-c1e2a1833245

**Comment by Barrysv** [comment]
@PaulAnnekov pip installed pyxiaomigateway0.10.10 and tested your script again a few times - log attached
[rpi_20181016_112320.txt](https://github.com/Danielhiversen/PyXiaomiGateway/files/2481462/rpi_20181016_112320.txt)

**Pull request merged**
