### PR TITLE
regenerate cmd with new token

### PR DESCRIPTION
**Pull request by Danielhiversen**
After we ask for a new token we have to regenerate the comand

@syssi : Could check this?

### CODE REVIEW

**Comment by syssi** [comment]
I will try to test the functionality by filtering the multicast traffic tomorrow!

**Comment by syssi** [comment]
I was able to filter the multicast traffic by
```
iptables -A INPUT -p udp -d 224.0.0.50 -j DROP
```
executed on the homeassistant host. This is the expected network traffic:



```
# First try
$ ngrep -l -q udp and host 192.168.132.3

U 192.168.132.2:54560 -> 192.168.132.3:9898
  {"data": {"mid": 10001, "vol": 1, "key": "7f8d38bf2f1367ecbe0f3a0c67eb8936"}, "cmd": "write", "sid": "34ce0088db0b"}                                                           

U 192.168.132.3:9898 -> 192.168.132.2:54560
  {"cmd":"write_ack","sid":"34ce0088db0b","data":"{\"error\":\"Invalid key\"}"}                                                                                                  

U 192.168.132.2:54560 -> 192.168.132.3:9898
  {"cmd" : "get_id_list"}                                                                                                                                                        

U 192.168.132.3:9898 -> 192.168.132.2:54560
  {"cmd":"get_id_list_ack","sid":"34ce0088db0b","token":"Imt6Sb7zCBInddjX","data":"[...]"}                                                                                                                                                            

U 192.168.132.2:54560 -> 192.168.132.3:9898
  {"data": {"mid": 10001, "vol": 1, "key": "b89fc354c108ef90849ddebee2268a81"}, "cmd": "write", "sid": "34ce0088db0b"}                                                           

# Gateway plays the selected ringtone

U 192.168.132.3:9898 -> 192.168.132.2:54560
  {"cmd":"write_ack","model":"gateway","sid":"34ce0088db0b","short_id":0,"data":"{\"rgb\":1694498815,\"illumination\":1292,\"proto_version\":\"1.0.9\"}"}                        
```

```
# Second try
$ ngrep -l -q udp and host 192.168.132.3

U 192.168.132.2:54560 -> 192.168.132.3:9898
  {"data": {"mid": 10001, "vol": 1, "key": "b89fc354c108ef90849ddebee2268a81"}, "cmd": "write", "sid": "34ce0088db0b"}                                                           

U 192.168.132.3:9898 -> 192.168.132.2:54560
  {"cmd":"write_ack","sid":"34ce0088db0b","data":"{\"error\":\"Invalid key\"}"}                                                                                                  

U 192.168.132.2:54560 -> 192.168.132.3:9898
  {"cmd" : "get_id_list"}                                                                                                                                                        

U 192.168.132.3:9898 -> 192.168.132.2:54560
  {"cmd":"get_id_list_ack","sid":"34ce0088db0b","token":"z9kIXLRRvF05PTAA","data":"[...]"}                                                                                                                                                            

U 192.168.132.2:54560 -> 192.168.132.3:9898
  {"data": {"mid": 10001, "vol": 1, "key": "e4a330b475e13ef9df9883f83fc3a6cd"}, "cmd": "write", "sid": "34ce0088db0b"}                                                           

# Gateway plays the selected ringtone

U 192.168.132.3:9898 -> 192.168.132.2:54560
  {"cmd":"write_ack","model":"gateway","sid":"34ce0088db0b","short_id":0,"data":"{\"rgb\":1694498815,\"illumination\":1292,\"proto_version\":\"1.0.9\"}"}
```

**Comment by syssi** [comment]
New insight: A single lost token triggers an "invalid key" error. There are no multiple valid tokens at a time / no window of valid tokens.

**Comment by Danielhiversen** [comment]
That is good to now

**Pull request merged**
