### PR TITLE
change to cryptography

### PR DESCRIPTION
**Pull request by Danielhiversen**

### CODE REVIEW

**Comment by Danielhiversen** [comment]
@syssi Could you try this fix? I have only tested it with controlling the gateway lights.
Many people are struggling with pycrypto, and I hope this will make it easier

**Comment by syssi** [comment]
Alright. I will give it a try!

**Comment by syssi** [comment]
Good job! Works fine. Just tested with a zigbee plug.

**Comment by macropin** [comment]
I wish this change were never made. `cryptography` depends on `cffi` which cannot be built on Raspbian (Bananapi) without segfaulting gcc-4.9.

**Comment by Danielhiversen** [comment]
This made it much easier to use PyXiaomiGateway for many users, and you are the first one who have reported any problem.

You are welcome to suggest a better solution

**Comment by macropin** [comment]
I upgraded Raspbian from Jessie to Stretch and was able to compile `cffi` with the newer gcc. So all good.

**Pull request merged**
