### PR TITLE
Bind always to the multicast address

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Comment by Chupaka** [comment]
Hey @syssi, any background on this change? Dug into this while upgrading my setup, and that's why I need binding to the 0.0.0.0 address: https://github.com/Danielhiversen/PyXiaomiGateway/issues/191

**Comment by Chupaka** [comment]
@syssi ?..

**Comment by syssi** [comment]
It's hard to explain. Without this change docker containers loose the multicast group membership after a while and all sub devices are marked as unavailable.

**Comment by Chupaka** [comment]
The same for me, but _with_ this change 😅 Can it be made configurable?..

**Pull request merged**
