### PR TITLE
Add four new Aqara button models

### PR DESCRIPTION
**Pull request by crhan**
fix issue #162  and #173 

add four models

- switch_b1lacn02
- switch_b2lacn02
- switch_b2nacn02
- remote.b286acn02

### CODE REVIEW

**Comment by syssi** [comment]
Could you add the new models to the correct line (equal device type) of the array?

**Comment by chewbh** [comment]
This change also requires the devices to be added in `xiaomi_aqara` component to correctly add the devices to home assistant. If not, this only remove the error messages for not recognized devices in the logs. I tested the integration in my environment with the devices. home-assistant/core#37985

**Comment by lxh0508** [comment]
I try add the models to __init__.py. but still can not find the wall switch in the ui of homeassistant.

WARNING (SyncWorker_0) [miio.gateway] Unknown subdevice type SubDeviceInfo(sid='lumi.158d0004650603', type_id=170, unknown=1, unknown2=61, fw_ver=1) discovered, of Xiaomi gateway with ip: 192.168.1.163 | stdout

Home-assistant version: 0.113
OS: Docker in DSM6.2.3-U2

**Comment by oxelwhy** [comment]
Does this add support for Aqara Switch D1 3 gang as well - "lumi.switch.l3acn3"?

Thanks.

**Comment by syssi** [comment]
No.

**Comment by oxelwhy** [comment]
Would it be possible to add this support?

**Comment by EvgenaNet** [comment]
Still not working D1...
2020-12-08 11:21:54.950 Status: XiaomiGateway (ID=10): unhandled model: 'switch_b2lacn02', name: 'Unknown Xiaomi device'
2020-12-08 11:21:54.950 Status: {"cmd":"report","model":"switch_b2lacn02","sid":"158d000521a92b","short_id":36577,"data":"{\"channel_0\":\"on\"}"}

**Pull request merged**
